<?php

namespace AppBundle\Repository;

/**
 * flipbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class flipbookRepository extends \Doctrine\ORM\EntityRepository
{
}
