<?php

namespace AppBundle\Repository;

/**
 * flipbookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use AppBundle\Entity\flipbook;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;


class flipbookRepository extends EntityRepository
{

    /*
     * @return Query
     * */
    public function getAll()
    {
        return $this->getEntityManager()->createQuery('
            SELECT AppBundle:flipbook f
        ');
    }

    /**
     *
     * @param int $page
     *
     * @return
     */
}
